### ISSUE TITLE
Screenshots - getTile endpoint   

### ISSUE THREAD

**Issue by akash5100** [Helioviewer-Project/python-api#18]
endpoint details: https://api.helioviewer.org/docs/v2/api/api_groups/official_clients.html#gettile

**Comment by akash5100** [comment]
This endpoint is now in the screenshot group?

**Comment by nabobalis** [comment]
Do you mean its moved?

**Comment by akash5100** [comment]
yes, not sure. Daniel changed the title.

**Comment by nabobalis** [comment]
I assume it was moved but that shouldn't change anything.
