### ISSUE TITLE
Add a way to change the BASEURL

### ISSUE THREAD

**Issue by nabobalis** [Helioviewer-Project/python-api#24]
There are several (I am unclear how many) mirrors for Helioviewer and people might want to use a mirror instead of the main URL. So we will need to add a way to change this either as a keyword, a configuration option or even a system environment variable.

**Comment by wafels** [comment]
There are at least three URLs.

**Comment by nabobalis** [comment]
Do you want us to test against all three in our tests?

**Comment by nabobalis** [comment]
We also have the beta URL: [api.beta.helioviewer.org](http://api.beta.helioviewer.org/)
