### ISSUE TITLE
user must pass lower case "json" instead of "Json" 

### ISSUE THREAD

**Issue by akash5100** [Helioviewer-Project/python-api#26]
Currently, "Json" is converted into "json" with this [method](https://github.com/Helioviewer-Project/python-api/pull/21/files#diff-4b73abe47d9fc20a0302a0d4645d7382941a58a31282104e86ce5349e70ae541R9).

**Comment by akash5100** [comment]
Fixed in PR #21 with [this commit](https://github.com/Helioviewer-Project/python-api/pull/21/commits/7c6c5b95dd7fa33f6bc09dde7fa0bd81ea72a99f)

**Comment by nabobalis** [comment]
This should only be closed when the pull request is merged.
